language: node_js
dist: trusty
node_js:
  - node
cache:
  yarn: true
  directories:
    - "~/.cache"
install:
  - yarn install --frozen-lockfile
  - yarn global add codecov
script:
  - yarn prettier --check
  - yarn test && codecov
  - yarn build:esm
